import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }



import '@/public/css/animate.css';
import '@/public/css/aos.css';
import '@/public/css/bootstrap.min.css';
import '@/public/css/flaticon.css';
import '@/public/css/bootstrap/bootstrap-grid.css';
import '@/public/css/bootstrap/bootstrap-reboot.css';
import '@/public/css/bootstrap/bootstrap-utilities.css';
import '@/public/css/bootstrap/vendor/_rfs.css';
// import '@/public/fonts/flaticon/font/flaticon.css';
// import '@/public/js';





import '@/public/css/glightbox.min.css';
// import '@/public/vendor/remixicon/remixicon.css';
import '@/public/css/datepicker.min.css';
import '@/public/css/tiny-slider.css';


//                              js file 

import '@/public/js/aos';
// import '@/public/js/bootstrap.bundle.min.js';







// import '@/public/vendor/swiper/swiper-bundle.min.css';
import '@/public/css/style.css';
import { Nunito, Old_Standard_TT } from 'next/font/google';
// import 'bootstrap/dist/css/bootstrap.css';
import '../public/css/bootstrap.min.css';
// import '../public/css/style.css';
import './BootstrapClient';


import '../public/css/frotawesome/all.css';
import '../public/css/frotawesome/brands.css';

import './globals.css';
import Script from 'next/script';

const nunito = Nunito({ subsets: ['latin'], weight: ['300', '400', '600', '700'] });
const oldStandardTT = Old_Standard_TT({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${nunito.className} ${oldStandardTT.className}`}>
      <head>
        <title>unwind </title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/4.5.6/css/ionicons.min.css" />
      </head>
      <body>
        {children}
         {/* <Script src="/js/bootstrap.bundle.min.js" strategy="beforeInteractive" /> */}
        {/* <Script src="/js/tiny-slider.js" strategy="beforeInteractive" /> */}
        {/* <Script src="/js/glightbox.min.js" strategy="beforeInteractive" />  */}
        {/* <Script src="https://kit.fontawesome.com/62efa4f0b6.js" crossorigin="anonymous"></Script> */}

        {/* <Script src="/js/datepicker.min.js" strategy="beforeInteractive" /> */}
        <Script src="/js/bootstrap.bundle.min.js"></Script>
        {/* <Script
          src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&sensor=false"
          strategy="beforeInteractive"
        /> */}
        {/* <Script src="/js/google-map.js" strategy="beforeInteractive" /> */}
        {/* <Script src="/public/js/google-map.js" strategy="beforeInteractive" /> */}

        {/* <Script src="/js/main.js" strategy="beforeInteractive" /> */}
      </body>
    </html>
  );
}
